trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - AzureDevOps/*  # This folder change won't trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'secrer-santa-secretsanta-f4465ce8-e6e6-4c46-b979-67aea42c5fb1'  # Update with your actual connection name
  tfVarsFile: 'AzureDevOps\Infrastructure\azure-vm\terraform.tfvars'
  terraformVersion: '1.6.0'

stages:
- stage: Deploy_VM
  jobs:
  - job: Terraform
    steps:

    - task: AzureCLI@2
      displayName: '🔐 Azure Login'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logged in to Azure:"
          az account show

    - script: |
        echo "⬇️ Installing Terraform $(terraformVersion)..."
        curl -sLo terraform.zip https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: '📦 Install Terraform CLI'

    - script: |
        echo "📁 Initializing Terraform..."
        terraform init
      displayName: '🔧 Terraform Init'

    - script: |
        echo "🔍 Validating Terraform..."
        terraform validate
      displayName: '✅ Terraform Validate'

    - script: |
        echo "🧠 Planning Terraform..."
        terraform plan -var "admin_password=$(admin_password)" -var-file="$(tfVarsFile)" -out=tfplan.out
      displayName: '📝 Terraform Plan'

    - script: |
        echo "🚀 Applying Terraform..."
        terraform apply -auto-approve tfplan.out
      displayName: '🚀 Terraform Apply'